version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor-v2:latest generate_cohort --cohort-definition analysis/study_definition.py --output output/input.csv
    outputs:
      highly_sensitive:
        cohort: output/input.csv
